[[redirects]]
  from = "/getword"
  to = "/.netlify/functions/getword/getword.js"
  status = 200

[[redirects]]
  from = "/kulturnav/api/"
  to = "https://kulturnav.org/api/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200



[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"

[build]
  functions = "functions/"

[dev]
  functions = "functions/"
